version: '3'

services: 
  web: 
    image: go/test:1.0
    build: ./web
    container_name: go_app
    tty: true
    ports: 
      - 8080:8080
    stdin_open: true
    volumes: 
      - ../web:/home/user1/dev